# Generated by Django 4.1.5 on 2024-09-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name of Category')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('img_categories', models.ImageField(blank=True, upload_to='', verbose_name='Category Image')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug of Sub Category')),
                ('img_item_category', models.ImageField(blank=True, upload_to='', verbose_name='Sub Category Image')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.categories')),
            ],
        ),
    ]
