# Generated by Django 4.1.5 on 2024-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsToPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name='User Id')),
                ('json_data', models.TextField(verbose_name='Json Data')),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='User ID')),
                ('product_id', models.CharField(max_length=125, verbose_name='Product ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
            ],
        ),
    ]
