# Generated by Django 4.1.5 on 2024-09-14 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug of Product')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='Product ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product price')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Product Quantity')),
                ('user_id', models.CharField(max_length=50, verbose_name='UserID')),
                ('products_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SearchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=60, verbose_name='Model')),
                ('brand', models.CharField(blank=True, max_length=60, verbose_name='Brand')),
                ('year', models.IntegerField(blank=True, verbose_name='Year')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Size')),
                ('place', models.CharField(blank=True, max_length=100, verbose_name='Place')),
                ('search_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productname')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, upload_to='product_video/%Y/%m/%d', verbose_name='Product video file')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productname')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImgFileSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(db_index=True, default=False, verbose_name='Main picture')),
                ('img_file', models.ImageField(blank=True, upload_to='product_img/%Y/%m/%d', verbose_name='Product img file')),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productname')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImgFileHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(blank=True, upload_to='', verbose_name='Product img file')),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productname')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Description title')),
                ('description_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productname')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_description', models.TextField(blank=True, verbose_name='Product description')),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productdescription')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.TextField(blank=True, verbose_name='HTML Table')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productdescription')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionImgFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.ImageField(blank=True, upload_to='', verbose_name='Description Img file')),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.descriptiontext')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='descriptio_media/file/%Y/%m/%d', verbose_name='Descriptio file')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productdescription')),
            ],
        ),
    ]
