# Generated by Django 4.1.5 on 2024-09-18 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Brand')),
                ('year', models.IntegerField(blank=True, default=None, null=True, verbose_name='Year')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Price')),
                ('brand_choices_to_select', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Brand_choices_to_select')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productname')),
            ],
        ),
    ]
